import fs from 'fs-extra';
import path from 'path';
import chalk from 'chalk';
import ora from 'ora';

interface AuditResult {
    secrets: string[];
    todos: string[];
    logs: string[];
}

const SECRET_REGEXES = [
    /sk-[a-zA-Z0-9]{48}/g, // OpenAI
    /key-[a-zA-Z0-9]{32}/g, // Generic
    /AIzaSy[a-zA-Z0-9_-]{33}/g, // Google
    /xox[baprs]-[a-zA-Z0-9-]+/g, // Slack
    /gh[pous]_[a-zA-Z0-9]{36}/g, // GitHub
    / "password": "[^"]+" /gi,
    / "secret": "[^"]+" /gi
];

export async function runAudit(projectPath: string = process.cwd()): Promise<AuditResult> {
    const results: AuditResult = {
        secrets: [],
        todos: [],
        logs: []
    };

    const spinner = ora('Scanning codebase for audit points...').start();

    const ignoreDirs = ['.git', 'node_modules', '.next', 'dist', 'build', 'out'];
    const extensions = ['.ts', '.tsx', '.js', '.jsx', '.py', '.go', '.md'];

    async function scanDir(dir: string) {
        const files = await fs.readdir(dir);

        for (const file of files) {
            const fullPath = path.join(dir, file);
            const stat = await fs.stat(fullPath);

            if (stat.isDirectory()) {
                if (!ignoreDirs.includes(file)) {
                    await scanDir(fullPath);
                }
            } else {
                const ext = path.extname(file);
                if (extensions.includes(ext)) {
                    await auditFile(fullPath);
                }
            }
        }
    }

    async function auditFile(filePath: string) {
        const content = await fs.readFile(filePath, 'utf-8');
        const relativePath = path.relative(projectPath, filePath);

        // Secrets
        for (const regex of SECRET_REGEXES) {
            const matches = content.match(regex);
            if (matches) {
                matches.forEach(m => results.secrets.push(`${relativePath}: Potential secret found`));
            }
        }

        // TODOs
        const todoLines = content.split('\n').filter(line => line.includes('TODO') || line.includes('FIXME'));
        todoLines.forEach(line => results.todos.push(`${relativePath}: ${line.trim()}`));

        // Logs
        const logLines = content.split('\n').filter(line => line.includes('console.log('));
        logLines.forEach(line => results.logs.push(`${relativePath}: ${line.trim()}`));
    }

    try {
        await scanDir(projectPath);
        spinner.succeed(`Scan complete. Found ${results.secrets.length} secrets, ${results.todos.length} TODOs, and ${results.logs.length} logs.`);

        await updateMemoryFile(projectPath, results);

        return results;
    } catch (err: any) {
        spinner.fail(`Audit failed: ${err.message}`);
        throw err;
    }
}

async function updateMemoryFile(projectPath: string, results: AuditResult) {
    const memoryPath = path.join(projectPath, 'MEMORY.md');
    let memoryContent = '';

    if (await fs.pathExists(memoryPath)) {
        memoryContent = await fs.readFile(memoryPath, 'utf-8');
    } else {
        memoryContent = '# Project Memory\n\nGenerated by mkagent.\n';
    }

    const auditSection = `
## Code Audit & Health (Auto-generated)
> [!IMPORTANT]
> This section is automatically maintained by \`mkagent audit\`. Do not manually edit.

### 🔐 Potential Secrets
${results.secrets.length > 0 ? results.secrets.map(s => `- ${s}`).join('\n') : '- No hardcoded secrets detected.'}

### 📝 Open TODOs & FIXMEs
${results.todos.length > 0 ? results.todos.map(t => `- ${t}`).join('\n') : '- Codebase is clean of TODOs.'}

### 🔍 Debug Logs
${results.logs.length > 0 ? results.logs.map(l => `- ${l}`).join('\n') : '- No stray console.logs found.'}

---
*Last audited on: ${new Date().toLocaleString()}*
`;

    // Replace existing section or append
    const sectionStart = memoryContent.indexOf('## Code Audit & Health');
    if (sectionStart !== -1) {
        const sectionEnd = memoryContent.indexOf('---', sectionStart + 22);
        if (sectionEnd !== -1) {
            const before = memoryContent.substring(0, sectionStart);
            const after = memoryContent.substring(sectionEnd + 3);
            memoryContent = before + auditSection + after;
        } else {
            memoryContent = memoryContent.substring(0, sectionStart) + auditSection;
        }
    } else {
        memoryContent += auditSection;
    }

    await fs.writeFile(memoryPath, memoryContent);
}
